# fly.toml app configuration file generated for rrees-weight-tracker on 2023-08-13T10:41:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rrees-weight-tracker"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
